export const CLEAR_STATE = "CLEAR_STATE";

// Root store
export const SET_ENTITY = "SET_ENTITY";
export const ADD_ENTITY = "ADD_ENTITY";

// UI
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const CHANGE_SIDEBAR_ACTIVE_TAB = "CHANGE_SIDEBAR_ACTIVE_TAB";

// Builder
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const SET_INGREDIENT_QUANTITY = "SET_INGREDIENT_QUANTITY";
export const INCREMENT_INGREDIENT_QUANTITY = "INCREMENT_INGREDIENT_QUANTITY";

// Order
export const PUSH_ORDER = "PUSH_ORDER";
export const PUSH_MISC = "PUSH_MISC";
export const SET_MISC_COUNT = "SET_MISC_COUNT";
export const SET_ORDER_COUNT = "SET_ORDER_COUNT";

// Cart
export const SET_RECEIVE = "SET_RECEIVE";
